version: '3.4'

services:
  processo-db:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: processo_service
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - regin-network
      
  regin-processo-service:
    image: pscs/regin-processo-service
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - processo-db
    environment:
      TZ: America/Sao_Paulo     
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: admin123
      SPRING.DATASOURCE.URL: jdbc:mysql://processo-db:3308/processo_service?useSSL=false&serverTimezono=America/Sao_Paulo&enabledTLSProtocols=TLSv1.2  
    networks:
      - regin-network
networks:
  regin-network:
    driver: bridge
    